services:
  - type: web
    name: waste-detection-backend
    env: python
    buildCommand: bash build.sh
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: WANDB_DISABLED
        value: "true"
      - key: YOLO_VERBOSE
        value: "false"
