services:
  - type: web
    name: waste-detection-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: WANDB_DISABLED
        value: "true"
      - key: YOLO_VERBOSE
        value: "false"
